# Deep learning CS332 Laboratory 5,6?

https://huggingface.co/tugstugi/wav2vec2-large-xlsr-53-mongolian
https://colab.research.google.com/github/patrickvonplaten/notebooks/blob/master/Fine_Tune_XLS_R_on_Common_Voice.ipynb#scrollTo=YELVqGxMxnbG

In [ ]:
import os
from datasets import load_dataset, Audio, concatenate_datasets


base_dir = "/home/gantumur/Documents/DL/Lab_commonvoice/data/cv-corpus-24.0-2025-12-05-mn/cv-corpus-24.0-2025-12-05/mn"

data_files = {
    "train": os.path.join(base_dir, "train.tsv"),
    "validation": os.path.join(base_dir, "dev.tsv"),
    "test": os.path.join(base_dir, "test.tsv")
}

dataset = load_dataset("csv", data_files=data_files, delimiter="\t")

common_voice_train = concatenate_datasets(
    [dataset["train"], dataset["validation"]])
common_voice_test = dataset["test"]

def attach_audio_paths(batch):
    batch["audio"] = os.path.join(base_dir, "clips", batch["path"])
    return batch


common_voice_train = common_voice_train.map(attach_audio_paths)
common_voice_test = common_voice_test.map(attach_audio_paths)

common_voice_train = common_voice_train.cast_column(
    "audio", Audio(sampling_rate=16_000))
common_voice_test = common_voice_test.cast_column(
    "audio", Audio(sampling_rate=16_000))

print(f"Training set size: {len(common_voice_train)}")
print(f"Test set size: {len(common_voice_test)}")

/home/gantumur/miniconda3/envs/env/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Training set size: 4084
Test set size: 1934

In [2]:
common_voice_train = common_voice_train.remove_columns(["accents", "age", "client_id", "down_votes", "gender", "locale", "segment", "up_votes", "sentence_id", "sentence_domain", "variant"])
common_voice_test = common_voice_test.remove_columns(
    ["accents", "age", "client_id", "down_votes", "gender", "locale", "segment", "up_votes", "sentence_id", "sentence_domain", "variant"])

In [3]:
print(common_voice_train)

Dataset({
    features: ['path', 'sentence', 'audio'],
    num_rows: 4084
})

In [4]:
print(common_voice_test)

Dataset({
    features: ['path', 'sentence', 'audio'],
    num_rows: 1934
})

In [5]:
from datasets import ClassLabel
import random
import pandas as pd
from IPython.display import display, HTML

def show_random_elements(dataset, num_examples=10):
    assert num_examples <= len(dataset), "Can't pick more elements than there are in the dataset."
    picks = []
    for _ in range(num_examples):
        pick = random.randint(0, len(dataset)-1)
        while pick in picks:
            pick = random.randint(0, len(dataset)-1)
        picks.append(pick)

    df = pd.DataFrame(dataset[picks])
    display(HTML(df.to_html()))

In [6]:
show_random_elements(common_voice_train.remove_columns(["path", "audio"]), num_examples=10)

In [7]:
import re
chars_to_remove_regex = '[\,\?\.\!\-\;\:\"\“\%\‘\”\\«\»\'\t\n]'

def remove_special_characters(batch):
    batch["sentence"] = re.sub(chars_to_remove_regex, '', batch["sentence"]).lower()
    return batch

<>:2: SyntaxWarning: invalid escape sequence '\,'
<>:2: SyntaxWarning: invalid escape sequence '\,'
/tmp/ipykernel_29615/907185610.py:2: SyntaxWarning: invalid escape sequence '\,'
  chars_to_remove_regex = '[\,\?\.\!\-\;\:\"\“\%\‘\”\\«\»\'\t\n]'

In [8]:
common_voice_train = common_voice_train.map(remove_special_characters)
common_voice_test = common_voice_test.map(remove_special_characters)

In [9]:
chars_to_remove_regex = '[habcdegilnortx0123456789_fmpsuvw]'

def remove_special_characters(batch):
    batch["sentence"] = re.sub(chars_to_remove_regex, '', batch["sentence"]).lower()
    return batch
common_voice_train = common_voice_train.map(remove_special_characters)
common_voice_test = common_voice_test.map(remove_special_characters)

In [10]:
show_random_elements(common_voice_train.remove_columns(["path","audio"]))

In [11]:
def extract_all_chars(batch):
    all_text = " ".join(batch["sentence"])
    vocab = list(set(all_text))
    return {"vocab": [vocab], "all_text": [all_text]}

In [12]:
vocab_train = common_voice_train.map(extract_all_chars, batched=True, batch_size=-1, keep_in_memory=True, remove_columns=common_voice_train.column_names)
vocab_test = common_voice_test.map(extract_all_chars, batched=True, batch_size=-1, keep_in_memory=True, remove_columns=common_voice_test.column_names)

Map: 100%|██████████| 4084/4084 [00:00<00:00, 179779.15 examples/s]
Map: 100%|██████████| 1934/1934 [00:00<00:00, 287173.29 examples/s]

In [13]:
vocab_list = list(set(vocab_train["vocab"][0]) | set(vocab_test["vocab"][0]))

In [14]:
vocab_dict = {v: k for k, v in enumerate(sorted(vocab_list))}
vocab_dict

{' ': 0,
 'а': 1,
 'б': 2,
 'в': 3,
 'г': 4,
 'д': 5,
 'е': 6,
 'ж': 7,
 'з': 8,
 'и': 9,
 'й': 10,
 'к': 11,
 'л': 12,
 'м': 13,
 'н': 14,
 'о': 15,
 'п': 16,
 'р': 17,
 'с': 18,
 'т': 19,
 'у': 20,
 'ф': 21,
 'х': 22,
 'ц': 23,
 'ч': 24,
 'ш': 25,
 'ъ': 26,
 'ы': 27,
 'ь': 28,
 'э': 29,
 'ю': 30,
 'я': 31,
 'ё': 32,
 'ү': 33,
 'ө': 34}

In [15]:
vocab_dict["|"] = vocab_dict[" "]
del vocab_dict[" "]

In [16]:
# vocab_dict["|"] = vocab_dict[" "]
# del vocab_dict["h"]

In [17]:
# vocab_dict["[UNK]"] = len(vocab_dict)
# vocab_dict["[PAD]"] = len(vocab_dict)
len(vocab_dict)

35

In [18]:
import json
with open('vocab.json', 'w') as vocab_file:
    json.dump(vocab_dict, vocab_file)

In [19]:
from transformers import Wav2Vec2CTCTokenizer

tokenizer = Wav2Vec2CTCTokenizer.from_pretrained("./", unk_token="[UNK]", pad_token="[PAD]", word_delimiter_token="|")

In [20]:
from transformers import Wav2Vec2FeatureExtractor

feature_extractor = Wav2Vec2FeatureExtractor(feature_size=1, sampling_rate=16000, padding_value=0.0, do_normalize=True, return_attention_mask=True)

In [21]:
from transformers import Wav2Vec2Processor

processor = Wav2Vec2Processor(feature_extractor=feature_extractor, tokenizer=tokenizer)

In [22]:
common_voice_train[0]["path"]

'common_voice_mn_21799896.mp3'

In [23]:
common_voice_train[0]["audio"]

{'path': '/home/gantumur/Documents/DL/Lab_commonvoice/data/cv-corpus-24.0-2025-12-05-mn/cv-corpus-24.0-2025-12-05/mn/clips/common_voice_mn_21799896.mp3',
 'array': array([-1.17961196e-16,  2.08166817e-17, -9.02056208e-17, ...,
         2.21929241e-07,  2.48354900e-06, -9.85941142e-07], shape=(103296,)),
 'sampling_rate': 16000}

In [24]:
import datasets

In [25]:
common_voice_train = common_voice_train.cast_column("audio", datasets.features.audio.Audio(sampling_rate=16_000))
common_voice_test = common_voice_test.cast_column("audio", datasets.features.audio.Audio(sampling_rate=16_000))

In [28]:
import IPython.display as ipd
import numpy as np
import random

rand_int = random.randint(0, len(common_voice_train)-1)

print(common_voice_train[rand_int]["sentence"])
ipd.Audio(data=common_voice_train[rand_int]["audio"]["array"], autoplay=True, rate=16000)

ямар нэгэн үйлдэл хийснээ хожим тэрээр огт санахгүй

In [29]:
common_voice_train[0]["audio"]["array"]

array([-1.17961196e-16,  2.08166817e-17, -9.02056208e-17, ...,
        2.21929241e-07,  2.48354900e-06, -9.85941142e-07], shape=(103296,))

In [30]:
rand_int = random.randint(0, len(common_voice_train)-1)

print("Target text:", common_voice_train[rand_int]["sentence"])
print("Input array shape:", common_voice_train[rand_int]["audio"]["array"].shape)
print("Sampling rate:", common_voice_train[rand_int]["audio"]["sampling_rate"])

Target text: авиа чимээ чагнасаар би зогсоогоороо унтсан
Input array shape: (52992,)
Sampling rate: 16000

In [31]:
def prepare_dataset(batch):
    audio = batch["audio"]

    # batched output is "un-batched"
    batch["input_values"] = processor(audio["array"], sampling_rate=audio["sampling_rate"]).input_values[0]
    batch["input_length"] = len(batch["input_values"])

    #with processor.as_target_processor(): # newer transformers lib removed as_target_processor()
    batch["labels"] = processor(text=batch["sentence"]).input_ids
    return batch

In [32]:
common_voice_train = common_voice_train.map(prepare_dataset, remove_columns=common_voice_train.column_names)
common_voice_test = common_voice_test.map(prepare_dataset, remove_columns=common_voice_test.column_names)

In [33]:
max_input_length_in_sec = 10.0
common_voice_train = common_voice_train.filter(lambda x: x < max_input_length_in_sec * processor.feature_extractor.sampling_rate, input_columns=["input_length"])

In [34]:
import torch

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Union

@dataclass
class DataCollatorCTCWithPadding:
    """
    Data collator that will dynamically pad the inputs received.
    Args:
        processor (:class:`~transformers.Wav2Vec2Processor`)
            The processor used for proccessing the data.
        padding (:obj:`bool`, :obj:`str` or :class:`~transformers.tokenization_utils_base.PaddingStrategy`, `optional`, defaults to :obj:`True`):
            Select a strategy to pad the returned sequences (according to the model's padding side and padding index)
            among:
            * :obj:`True` or :obj:`'longest'`: Pad to the longest sequence in the batch (or no padding if only a single
              sequence if provided).
            * :obj:`'max_length'`: Pad to a maximum length specified with the argument :obj:`max_length` or to the
              maximum acceptable input length for the model if that argument is not provided.
            * :obj:`False` or :obj:`'do_not_pad'` (default): No padding (i.e., can output a batch with sequences of
              different lengths).
    """

    processor: Wav2Vec2Processor
    padding: Union[bool, str] = True

    def __call__(self, features: List[Dict[str, Union[List[int], torch.Tensor]]]) -> Dict[str, torch.Tensor]:
        # split inputs and labels since they have to be of different lenghts and need
        # different padding methods
        input_features = [{"input_values": feature["input_values"]} for feature in features]
        label_features = [{"input_ids": feature["labels"]} for feature in features]

        batch = self.processor.pad(
            input_features,
            padding=self.padding,
            return_tensors="pt",
        )
        #with self.processor.as_target_processor():
        labels_batch = self.processor.tokenizer.pad(
            label_features,
            padding=self.padding,
            return_tensors="pt",
        )


        # replace padding with -100 to ignore loss correctly
        labels = labels_batch["input_ids"].masked_fill(labels_batch.attention_mask.ne(1), -100)

        batch["labels"] = labels

        return batch

In [35]:
data_collator = DataCollatorCTCWithPadding(processor=processor, padding=True)

In [36]:
from datasets import load_dataset, Audio
import evaluate

wer_metric = evaluate.load("wer")

In [37]:
def compute_metrics(pred):
    pred_logits = pred.predictions
    pred_ids = np.argmax(pred_logits, axis=-1)

    pred.label_ids[pred.label_ids == -100] = processor.tokenizer.pad_token_id

    pred_str = processor.batch_decode(pred_ids)
    # we do not want to group tokens when computing the metrics
    label_str = processor.batch_decode(pred.label_ids, group_tokens=False)

    wer = wer_metric.compute(predictions=pred_str, references=label_str)

    return {"wer": wer}

In [38]:
from transformers import Wav2Vec2ForCTC

model = Wav2Vec2ForCTC.from_pretrained(
    "tugstugi/wav2vec2-large-xlsr-53-mongolian",
    attention_dropout=0.0,
    hidden_dropout=0.0,
    feat_proj_dropout=0.0,
    mask_time_prob=0.05,
    layerdrop=0.0,
    ctc_loss_reduction="mean",
    pad_token_id=processor.tokenizer.pad_token_id,
    vocab_size=len(processor.tokenizer),
    ignore_mismatched_sizes=True
)

Loading weights: 100%|██████████| 424/424 [00:00<00:00, 2016.62it/s, Materializing param=wav2vec2.masked_spec_embed]
Wav2Vec2ForCTC LOAD REPORT from: tugstugi/wav2vec2-large-xlsr-53-mongolian
Key            | Status   |
---------------+----------+-------------------------------------------------------------------------------------------
lm_head.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([38, 1024]) vs model:torch.Size([39, 1024])
lm_head.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([38]) vs model:torch.Size([39])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

In [39]:
from transformers import TrainingArguments

training_args = TrainingArguments(
  output_dir='repo_name',
  group_by_length=True,
  per_device_train_batch_size=8,
  gradient_accumulation_steps=2,
  eval_strategy="steps",
  num_train_epochs=60,
  gradient_checkpointing=True,
  fp16=True,
  save_steps=400,
  eval_steps=400,
  logging_steps=400,
  learning_rate=3e-5, # decreased from 3e-4
  warmup_steps=1500,
  save_total_limit=2,
  push_to_hub=True,
  max_grad_norm=1.0
)

In [ ]:
from huggingface_hub import login 


login(token="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")

In [43]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    data_collator=data_collator,
    args=training_args,
    compute_metrics=compute_metrics,
    train_dataset=common_voice_train,
    eval_dataset=common_voice_test,
    processing_class=processor.feature_extractor,
)

In [44]:
trainer.train()

KeyboardInterrupt:

In [41]:
save_directory = "/home/gantumur/Documents/DL/Lab_commonvoice/models/mongolian-wav2vec2-trained1"

trainer.save_model(save_directory)
trainer.push_to_hub("Training complete!")

print(f"Model and processor successfully saved to {save_directory}")

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.38s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.72s/it]
Processing Files (2 / 2): 100%|██████████| 1.26GB / 1.26GB,  412MB/s
New Data Upload: 100%|██████████|  118MB /  118MB, 39.2MB/s
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.69s/it]
Processing Files (2 / 2): 100%|██████████| 1.26GB / 1.26GB,  412MB/s
New Data Upload: 100%|██████████|  118MB /  118MB, 39.2MB/s
No files have been modified since last commit. Skipping to prevent empty commit.

Model and processor successfully saved to /home/gantumur/Documents/DL/Lab_commonvoice/models/mongolian-wav2vec2-trained1

In [42]:
import gc
import torch

del model
del trainer
del processor

gc.collect()

torch.cuda.empty_cache()

print("GPU RAM cleared!")

GPU RAM cleared!

In [43]:
import IPython

IPython.Application.instance().kernel.do_shutdown(True)

{'status': 'ok', 'restart': True}

In [ ]:
# common_voice_test_transcription = load_dataset("common_voice", "mn", data_dir="./cv-corpus-6.1-2020-12-11", split="test")

# for i in range(10):
#   input_dict = processor(common_voice_test[i]["input_values"], return_tensors="pt", padding=True)

#   logits = model(input_dict.input_values.to("cuda")).logits

#   pred_ids = torch.argmax(logits, dim=-1)[0]

#   print(f"Prediction_{i}:")
#   print(processor.decode(pred_ids))

#   print(f"\nReference_{i}:")
#   print(common_voice_test[i]["sentence"].lower())

:

# Даалгавар 1
энэхүү сургалтын WER 48% бууруулах

# Даалгавар 2
өөрийн яриаг сургалтанд ашиглах

# Даалгавар 3
Бусад сүүлийн үеийн модел ашиглан сургах

# Хугацаа 4 долоо хоног